/**
 * Drizzle Migrations
 *
 * This file exports Drizzle-generated SQL migrations as JavaScript modules
 * for use in React Native/Expo where .sql files can't be directly imported.
 *
 * Generated by: drizzle-kit generate
 * DO NOT EDIT MANUALLY - regenerate using: pnpm drizzle-kit generate
 */

const fs = require("fs");
const path = require("path");

// Read the SQL migration file
const migration0000 = fs.readFileSync(
  path.join(__dirname, "0000_busy_menace.sql"),
  "utf8",
);

module.exports = {
  migrations: [
    {
      name: "0000_busy_menace",
      sql: migration0000,
    },
  ],
};
