-- GENERATED FILE. Do not edit.
-- Regenerate with: pnpm --filter=@prostcounter/api seed:achievements
--
-- The 90 achievement definitions, projected out of
-- packages/shared/src/achievements so that a fresh local database has the same
-- registry the app expects. This is the same projection the sync:achievements
-- script applies to a live database; both call buildRegistryRows().
--
-- Runs before seed.sql (see [db.seed] sql_paths in supabase/config.toml),
-- because seed.sql's QA block selects achievements by tier.
--
-- Rarity is deliberately absent: it is derived from tier, in TypeScript by
-- tierToRarity and in SQL by tier_to_rarity(int). Ids are left to the column
-- default, since nothing references an achievement by literal id.

INSERT INTO public.achievements
  (slug, series_id, tier, scope, category, points, icon, name, description, is_active)
VALUES
  ('drinks_total.t1', 'drinks_total', 1, 'festival', 'drinking', 10, 'masskrug', 'achievements.drinks_total.t1.name', 'achievements.drinks_total.t1.description', true),
  ('drinks_total.t2', 'drinks_total', 2, 'festival', 'drinking', 50, 'masskrug', 'achievements.drinks_total.t2.name', 'achievements.drinks_total.t2.description', true),
  ('drinks_total.t3', 'drinks_total', 3, 'festival', 'drinking', 150, 'masskrug', 'achievements.drinks_total.t3.name', 'achievements.drinks_total.t3.description', true),
  ('drinks_total.t4', 'drinks_total', 4, 'festival', 'drinking', 400, 'masskrug', 'achievements.drinks_total.t4.name', 'achievements.drinks_total.t4.description', true),
  ('drinks_day_max.t1', 'drinks_day_max', 1, 'festival', 'drinking', 15, 'sunburst-stein', 'achievements.drinks_day_max.t1.name', 'achievements.drinks_day_max.t1.description', true),
  ('drinks_day_max.t2', 'drinks_day_max', 2, 'festival', 'drinking', 60, 'sunburst-stein', 'achievements.drinks_day_max.t2.name', 'achievements.drinks_day_max.t2.description', true),
  ('drinks_day_max.t3', 'drinks_day_max', 3, 'festival', 'drinking', 160, 'sunburst-stein', 'achievements.drinks_day_max.t3.name', 'achievements.drinks_day_max.t3.description', true),
  ('drinks_day_max.t4', 'drinks_day_max', 4, 'festival', 'drinking', 420, 'sunburst-stein', 'achievements.drinks_day_max.t4.name', 'achievements.drinks_day_max.t4.description', true),
  ('drink_variety.t1', 'drink_variety', 1, 'festival', 'drinking', 10, 'three-glasses', 'achievements.drink_variety.t1.name', 'achievements.drink_variety.t1.description', true),
  ('drink_variety.t2', 'drink_variety', 2, 'festival', 'drinking', 45, 'three-glasses', 'achievements.drink_variety.t2.name', 'achievements.drink_variety.t2.description', true),
  ('drink_variety.t3', 'drink_variety', 3, 'festival', 'drinking', 120, 'three-glasses', 'achievements.drink_variety.t3.name', 'achievements.drink_variety.t3.description', true),
  ('drink_variety.t4', 'drink_variety', 4, 'festival', 'drinking', 300, 'three-glasses', 'achievements.drink_variety.t4.name', 'achievements.drink_variety.t4.description', true),
  ('volume_total.t1', 'volume_total', 1, 'festival', 'drinking', 10, 'measuring-jug', 'achievements.volume_total.t1.name', 'achievements.volume_total.t1.description', true),
  ('volume_total.t2', 'volume_total', 2, 'festival', 'drinking', 55, 'measuring-jug', 'achievements.volume_total.t2.name', 'achievements.volume_total.t2.description', true),
  ('volume_total.t3', 'volume_total', 3, 'festival', 'drinking', 150, 'measuring-jug', 'achievements.volume_total.t3.name', 'achievements.volume_total.t3.description', true),
  ('volume_total.t4', 'volume_total', 4, 'festival', 'drinking', 400, 'measuring-jug', 'achievements.volume_total.t4.name', 'achievements.volume_total.t4.description', true),
  ('tips_total.t1', 'tips_total', 1, 'festival', 'drinking', 15, 'coin-hand', 'achievements.tips_total.t1.name', 'achievements.tips_total.t1.description', true),
  ('tips_total.t2', 'tips_total', 2, 'festival', 'drinking', 60, 'coin-hand', 'achievements.tips_total.t2.name', 'achievements.tips_total.t2.description', true),
  ('tips_total.t3', 'tips_total', 3, 'festival', 'drinking', 150, 'coin-hand', 'achievements.tips_total.t3.name', 'achievements.tips_total.t3.description', true),
  ('tips_total.t4', 'tips_total', 4, 'festival', 'drinking', 380, 'coin-hand', 'achievements.tips_total.t4.name', 'achievements.tips_total.t4.description', true),
  ('spend_total.t1', 'spend_total', 1, 'festival', 'drinking', 15, 'purse', 'achievements.spend_total.t1.name', 'achievements.spend_total.t1.description', true),
  ('spend_total.t2', 'spend_total', 2, 'festival', 'drinking', 65, 'purse', 'achievements.spend_total.t2.name', 'achievements.spend_total.t2.description', true),
  ('spend_total.t3', 'spend_total', 3, 'festival', 'drinking', 170, 'purse', 'achievements.spend_total.t3.name', 'achievements.spend_total.t3.description', true),
  ('spend_total.t4', 'spend_total', 4, 'festival', 'drinking', 450, 'purse', 'achievements.spend_total.t4.name', 'achievements.spend_total.t4.description', true),
  ('days_attended.t1', 'days_attended', 1, 'festival', 'attendance', 10, 'calendar-check', 'achievements.days_attended.t1.name', 'achievements.days_attended.t1.description', true),
  ('days_attended.t2', 'days_attended', 2, 'festival', 'attendance', 50, 'calendar-check', 'achievements.days_attended.t2.name', 'achievements.days_attended.t2.description', true),
  ('days_attended.t3', 'days_attended', 3, 'festival', 'attendance', 150, 'calendar-check', 'achievements.days_attended.t3.name', 'achievements.days_attended.t3.description', true),
  ('days_attended.t4', 'days_attended', 4, 'festival', 'attendance', 400, 'calendar-check', 'achievements.days_attended.t4.name', 'achievements.days_attended.t4.description', true),
  ('attendance_streak.t1', 'attendance_streak', 1, 'festival', 'attendance', 20, 'chain-links', 'achievements.attendance_streak.t1.name', 'achievements.attendance_streak.t1.description', true),
  ('attendance_streak.t2', 'attendance_streak', 2, 'festival', 'attendance', 70, 'chain-links', 'achievements.attendance_streak.t2.name', 'achievements.attendance_streak.t2.description', true),
  ('attendance_streak.t3', 'attendance_streak', 3, 'festival', 'attendance', 180, 'chain-links', 'achievements.attendance_streak.t3.name', 'achievements.attendance_streak.t3.description', true),
  ('attendance_streak.t4', 'attendance_streak', 4, 'festival', 'attendance', 450, 'chain-links', 'achievements.attendance_streak.t4.name', 'achievements.attendance_streak.t4.description', true),
  ('tents_visited.t1', 'tents_visited', 1, 'festival', 'explorer', 15, 'tent-peaks', 'achievements.tents_visited.t1.name', 'achievements.tents_visited.t1.description', true),
  ('tents_visited.t2', 'tents_visited', 2, 'festival', 'explorer', 60, 'tent-peaks', 'achievements.tents_visited.t2.name', 'achievements.tents_visited.t2.description', true),
  ('tents_visited.t3', 'tents_visited', 3, 'festival', 'explorer', 160, 'tent-peaks', 'achievements.tents_visited.t3.name', 'achievements.tents_visited.t3.description', true),
  ('tents_visited.t4', 'tents_visited', 4, 'festival', 'explorer', 400, 'tent-peaks', 'achievements.tents_visited.t4.name', 'achievements.tents_visited.t4.description', true),
  ('festivals_attended.t1', 'festivals_attended', 1, 'lifetime', 'explorer', 20, 'ferris-wheel', 'achievements.festivals_attended.t1.name', 'achievements.festivals_attended.t1.description', true),
  ('festivals_attended.t2', 'festivals_attended', 2, 'lifetime', 'explorer', 90, 'ferris-wheel', 'achievements.festivals_attended.t2.name', 'achievements.festivals_attended.t2.description', true),
  ('festivals_attended.t3', 'festivals_attended', 3, 'lifetime', 'explorer', 220, 'ferris-wheel', 'achievements.festivals_attended.t3.name', 'achievements.festivals_attended.t3.description', true),
  ('festivals_attended.t4', 'festivals_attended', 4, 'lifetime', 'explorer', 500, 'ferris-wheel', 'achievements.festivals_attended.t4.name', 'achievements.festivals_attended.t4.description', true),
  ('festival_types.t1', 'festival_types', 1, 'lifetime', 'explorer', 15, 'compass-rose', 'achievements.festival_types.t1.name', 'achievements.festival_types.t1.description', true),
  ('festival_types.t2', 'festival_types', 2, 'lifetime', 'explorer', 70, 'compass-rose', 'achievements.festival_types.t2.name', 'achievements.festival_types.t2.description', true),
  ('festival_types.t3', 'festival_types', 3, 'lifetime', 'explorer', 190, 'compass-rose', 'achievements.festival_types.t3.name', 'achievements.festival_types.t3.description', true),
  ('festival_types.t4', 'festival_types', 4, 'lifetime', 'explorer', 450, 'compass-rose', 'achievements.festival_types.t4.name', 'achievements.festival_types.t4.description', true),
  ('groups_joined.t1', 'groups_joined', 1, 'festival', 'social', 15, 'three-figures', 'achievements.groups_joined.t1.name', 'achievements.groups_joined.t1.description', true),
  ('groups_joined.t2', 'groups_joined', 2, 'festival', 'social', 55, 'three-figures', 'achievements.groups_joined.t2.name', 'achievements.groups_joined.t2.description', true),
  ('groups_joined.t3', 'groups_joined', 3, 'festival', 'social', 150, 'three-figures', 'achievements.groups_joined.t3.name', 'achievements.groups_joined.t3.description', true),
  ('groups_joined.t4', 'groups_joined', 4, 'festival', 'social', 380, 'three-figures', 'achievements.groups_joined.t4.name', 'achievements.groups_joined.t4.description', true),
  ('friends_added.t1', 'friends_added', 1, 'lifetime', 'social', 15, 'clasped-hands', 'achievements.friends_added.t1.name', 'achievements.friends_added.t1.description', true),
  ('friends_added.t2', 'friends_added', 2, 'lifetime', 'social', 60, 'clasped-hands', 'achievements.friends_added.t2.name', 'achievements.friends_added.t2.description', true),
  ('friends_added.t3', 'friends_added', 3, 'lifetime', 'social', 170, 'clasped-hands', 'achievements.friends_added.t3.name', 'achievements.friends_added.t3.description', true),
  ('friends_added.t4', 'friends_added', 4, 'lifetime', 'social', 420, 'clasped-hands', 'achievements.friends_added.t4.name', 'achievements.friends_added.t4.description', true),
  ('photos_uploaded.t1', 'photos_uploaded', 1, 'festival', 'social', 10, 'camera-shutter', 'achievements.photos_uploaded.t1.name', 'achievements.photos_uploaded.t1.description', true),
  ('photos_uploaded.t2', 'photos_uploaded', 2, 'festival', 'social', 55, 'camera-shutter', 'achievements.photos_uploaded.t2.name', 'achievements.photos_uploaded.t2.description', true),
  ('photos_uploaded.t3', 'photos_uploaded', 3, 'festival', 'social', 155, 'camera-shutter', 'achievements.photos_uploaded.t3.name', 'achievements.photos_uploaded.t3.description', true),
  ('photos_uploaded.t4', 'photos_uploaded', 4, 'festival', 'social', 400, 'camera-shutter', 'achievements.photos_uploaded.t4.name', 'achievements.photos_uploaded.t4.description', true),
  ('reactions_given.t1', 'reactions_given', 1, 'festival', 'social', 10, 'spark-heart', 'achievements.reactions_given.t1.name', 'achievements.reactions_given.t1.description', true),
  ('reactions_given.t2', 'reactions_given', 2, 'festival', 'social', 50, 'spark-heart', 'achievements.reactions_given.t2.name', 'achievements.reactions_given.t2.description', true),
  ('reactions_given.t3', 'reactions_given', 3, 'festival', 'social', 140, 'spark-heart', 'achievements.reactions_given.t3.name', 'achievements.reactions_given.t3.description', true),
  ('reactions_given.t4', 'reactions_given', 4, 'festival', 'social', 350, 'spark-heart', 'achievements.reactions_given.t4.name', 'achievements.reactions_given.t4.description', true),
  ('group_wins.t1', 'group_wins', 1, 'lifetime', 'competitive', 40, 'laurel-cup', 'achievements.group_wins.t1.name', 'achievements.group_wins.t1.description', true),
  ('group_wins.t2', 'group_wins', 2, 'lifetime', 'competitive', 130, 'laurel-cup', 'achievements.group_wins.t2.name', 'achievements.group_wins.t2.description', true),
  ('group_wins.t3', 'group_wins', 3, 'lifetime', 'competitive', 300, 'laurel-cup', 'achievements.group_wins.t3.name', 'achievements.group_wins.t3.description', true),
  ('group_wins.t4', 'group_wins', 4, 'lifetime', 'competitive', 600, 'laurel-cup', 'achievements.group_wins.t4.name', 'achievements.group_wins.t4.description', true),
  ('podium_finishes.t1', 'podium_finishes', 1, 'lifetime', 'competitive', 25, 'podium-steps', 'achievements.podium_finishes.t1.name', 'achievements.podium_finishes.t1.description', true),
  ('podium_finishes.t2', 'podium_finishes', 2, 'lifetime', 'competitive', 100, 'podium-steps', 'achievements.podium_finishes.t2.name', 'achievements.podium_finishes.t2.description', true),
  ('podium_finishes.t3', 'podium_finishes', 3, 'lifetime', 'competitive', 250, 'podium-steps', 'achievements.podium_finishes.t3.name', 'achievements.podium_finishes.t3.description', true),
  ('podium_finishes.t4', 'podium_finishes', 4, 'lifetime', 'competitive', 550, 'podium-steps', 'achievements.podium_finishes.t4.name', 'achievements.podium_finishes.t4.description', true),
  ('active_days.t1', 'active_days', 1, 'lifetime', 'dedication', 10, 'hourglass', 'achievements.active_days.t1.name', 'achievements.active_days.t1.description', true),
  ('active_days.t2', 'active_days', 2, 'lifetime', 'dedication', 50, 'hourglass', 'achievements.active_days.t2.name', 'achievements.active_days.t2.description', true),
  ('active_days.t3', 'active_days', 3, 'lifetime', 'dedication', 150, 'hourglass', 'achievements.active_days.t3.name', 'achievements.active_days.t3.description', true),
  ('active_days.t4', 'active_days', 4, 'lifetime', 'dedication', 400, 'hourglass', 'achievements.active_days.t4.name', 'achievements.active_days.t4.description', true),
  ('active_day_streak.t1', 'active_day_streak', 1, 'lifetime', 'dedication', 15, 'flame-steady', 'achievements.active_day_streak.t1.name', 'achievements.active_day_streak.t1.description', true),
  ('active_day_streak.t2', 'active_day_streak', 2, 'lifetime', 'dedication', 65, 'flame-steady', 'achievements.active_day_streak.t2.name', 'achievements.active_day_streak.t2.description', true),
  ('active_day_streak.t3', 'active_day_streak', 3, 'lifetime', 'dedication', 180, 'flame-steady', 'achievements.active_day_streak.t3.name', 'achievements.active_day_streak.t3.description', true),
  ('active_day_streak.t4', 'active_day_streak', 4, 'lifetime', 'dedication', 480, 'flame-steady', 'achievements.active_day_streak.t4.name', 'achievements.active_day_streak.t4.description', true),
  ('crowd_reports.t1', 'crowd_reports', 1, 'festival', 'dedication', 10, 'signal-flag', 'achievements.crowd_reports.t1.name', 'achievements.crowd_reports.t1.description', true),
  ('crowd_reports.t2', 'crowd_reports', 2, 'festival', 'dedication', 45, 'signal-flag', 'achievements.crowd_reports.t2.name', 'achievements.crowd_reports.t2.description', true),
  ('crowd_reports.t3', 'crowd_reports', 3, 'festival', 'dedication', 130, 'signal-flag', 'achievements.crowd_reports.t3.name', 'achievements.crowd_reports.t3.description', true),
  ('crowd_reports.t4', 'crowd_reports', 4, 'festival', 'dedication', 330, 'signal-flag', 'achievements.crowd_reports.t4.name', 'achievements.crowd_reports.t4.description', true),
  ('first_drink', NULL, 1, 'lifetime', 'drinking', 10, 'first-drop', 'achievements.first_drink.name', 'achievements.first_drink.description', true),
  ('opening_day', NULL, 2, 'festival', 'attendance', 80, 'sunrise-gate', 'achievements.opening_day.name', 'achievements.opening_day.description', true),
  ('closing_day', NULL, 2, 'festival', 'attendance', 80, 'sunset-gate', 'achievements.closing_day.name', 'achievements.closing_day.description', true),
  ('every_weekend_day', NULL, 3, 'festival', 'attendance', 220, 'double-sun', 'achievements.every_weekend_day.name', 'achievements.every_weekend_day.description', true),
  ('full_festival', NULL, 4, 'festival', 'attendance', 600, 'wiesn-crown', 'achievements.full_festival.name', 'achievements.full_festival.description', true),
  ('all_large_tents', NULL, 4, 'festival', 'explorer', 550, 'tent-ring', 'achievements.all_large_tents.name', 'achievements.all_large_tents.description', true),
  ('first_photo', NULL, 1, 'lifetime', 'social', 10, 'polaroid', 'achievements.first_photo.name', 'achievements.first_photo.description', true),
  ('created_group', NULL, 2, 'festival', 'social', 70, 'banner-pole', 'achievements.created_group.name', 'achievements.created_group.description', true),
  ('profile_complete', NULL, 1, 'lifetime', 'dedication', 15, 'id-card', 'achievements.profile_complete.name', 'achievements.profile_complete.description', true),
  ('wrapped_viewed', NULL, 2, 'lifetime', 'dedication', 60, 'ribbon-scroll', 'achievements.wrapped_viewed.name', 'achievements.wrapped_viewed.description', true)
ON CONFLICT (slug) DO NOTHING;
