/**
 * Standardized API Error Codes
 *
 * These codes are returned by the API and can be translated
 * by the frontend using i18n. The pattern is:
 *
 * API returns: { error: { code: "GROUP_NOT_FOUND", message: "..." } }
 * Frontend: t(`apiErrors.${error.code}`) -> "Group not found"
 */
export const ErrorCodes = {
  // Generic errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  DATABASE_ERROR: "DATABASE_ERROR",

  // Auth errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",

  // Group errors
  GROUP_NOT_FOUND: "GROUP_NOT_FOUND",
  NOT_GROUP_MEMBER: "NOT_GROUP_MEMBER",
  NOT_GROUP_CREATOR: "NOT_GROUP_CREATOR",
  ALREADY_GROUP_MEMBER: "ALREADY_GROUP_MEMBER",
  INVALID_INVITE_TOKEN: "INVALID_INVITE_TOKEN",
  CANNOT_REMOVE_SELF: "CANNOT_REMOVE_SELF",
  USER_NOT_GROUP_MEMBER: "USER_NOT_GROUP_MEMBER",

  // Attendance errors
  ATTENDANCE_NOT_FOUND: "ATTENDANCE_NOT_FOUND",
  DUPLICATE_ATTENDANCE: "DUPLICATE_ATTENDANCE",
  INVALID_DATE: "INVALID_DATE",
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
  DATE_OUTSIDE_FESTIVAL: "DATE_OUTSIDE_FESTIVAL",
  PRICE_BELOW_BASE: "PRICE_BELOW_BASE",

  // Festival errors
  FESTIVAL_NOT_FOUND: "FESTIVAL_NOT_FOUND",
  NO_ACTIVE_FESTIVAL: "NO_ACTIVE_FESTIVAL",

  // Tent errors
  TENT_NOT_FOUND: "TENT_NOT_FOUND",

  // Reservation errors
  RESERVATION_NOT_FOUND: "RESERVATION_NOT_FOUND",
  RESERVATION_ALREADY_CHECKED_IN: "RESERVATION_ALREADY_CHECKED_IN",
  RESERVATION_CANCELLED: "RESERVATION_CANCELLED",
  RESERVATION_START_IN_PAST: "RESERVATION_START_IN_PAST",
  RESERVATION_END_BEFORE_START: "RESERVATION_END_BEFORE_START",

  // Photo errors
  PHOTO_NOT_FOUND: "PHOTO_NOT_FOUND",
  PHOTO_UPLOAD_FAILED: "PHOTO_UPLOAD_FAILED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_NAME_TOO_LONG: "FILE_NAME_TOO_LONG",
  CAPTION_TOO_LONG: "CAPTION_TOO_LONG",

  // Achievement errors
  ACHIEVEMENT_NOT_FOUND: "ACHIEVEMENT_NOT_FOUND",

  // Location errors
  LOCATION_SESSION_NOT_FOUND: "LOCATION_SESSION_NOT_FOUND",
  LOCATION_SESSION_EXPIRED: "LOCATION_SESSION_EXPIRED",
  LOCATION_SESSION_ALREADY_ACTIVE: "LOCATION_SESSION_ALREADY_ACTIVE",
  INVALID_DURATION: "INVALID_DURATION",
  INVALID_COORDINATES: "INVALID_COORDINATES",
  INVALID_RADIUS: "INVALID_RADIUS",
  INVALID_PAGINATION: "INVALID_PAGINATION",

  // Profile errors
  PROFILE_NOT_FOUND: "PROFILE_NOT_FOUND",
  USERNAME_TAKEN: "USERNAME_TAKEN",

  // Wrapped errors
  WRAPPED_NOT_FOUND: "WRAPPED_NOT_FOUND",
  WRAPPED_NOT_READY: "WRAPPED_NOT_READY",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

/**
 * Helper to check if a value is a valid error code
 */
export function isErrorCode(value: unknown): value is ErrorCode {
  return (
    typeof value === "string" &&
    Object.values(ErrorCodes).includes(value as ErrorCode)
  );
}
