/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

// Placeholder - will be replaced when OpenAPI spec has actual routes
export type paths = Record<string, never>;

export type webhooks = Record<string, never>;

export interface components {
  schemas: Record<string, never>;
  responses: Record<string, never>;
  parameters: Record<string, never>;
  requestBodies: Record<string, never>;
  headers: Record<string, never>;
  pathItems: Record<string, never>;
}

export type $defs = Record<string, never>;

export type operations = Record<string, never>;
