create table "public"."attendance" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "date" date not null,
    "liters" smallint default '0'::smallint
);


alter table "public"."attendance" enable row level security;

CREATE UNIQUE INDEX attendance_pkey ON public.attendance USING btree (user_id, date);

alter table "public"."attendance" add constraint "attendance_pkey" PRIMARY KEY using index "attendance_pkey";

alter table "public"."attendance" add constraint "attendance_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."attendance" validate constraint "attendance_user_id_fkey";


