const { withDangerousMod } = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

/**
 * Config plugin that injects the WatchSessionBridge class into AppDelegate.swift
 * and activates it in application(_:didFinishLaunchingWithOptions:).
 *
 * Why merged into AppDelegate.swift instead of a separate file:
 *   AppDelegate.swift is already in the ProstCounter target's Sources build phase.
 *   Merging here avoids patching project.pbxproj, which is brittle. The class
 *   survives `expo prebuild --clean` automatically since it is regenerated by this plugin.
 */

const BRIDGE_CLASS_SNIPPET = `
// MARK: - WatchSessionBridge (injected by withWatchSessionBridge.js)

import os
import WatchConnectivity

private let watchBridgeLog = Logger(subsystem: "com.prostcounter.watch", category: "bridge")

/// Bridges App Group UserDefaults changes on the iPhone to the paired Apple Watch
/// via WCSession.updateApplicationContext (simulator-compatible) with a sendMessage
/// fast path when the watch app is reachable.
///
/// Flow:
///   JS (ExtensionStorage) → UserDefaults(suiteName:) → KVO here
///     → WCSession.sendMessage (if watch reachable, for real-time delivery)
///     → WCSession.updateApplicationContext (persistent, simulator-compatible)
final class WatchSessionBridge: NSObject {

  static let shared = WatchSessionBridge()

  private let appGroup = "group.com.prostcounter.shared"
  private let watchedKeys = ["accessToken", "refreshToken", "userId", "currentFestivalId", "expiresAt"]
  // Sentinel keys: JS writes a fresh nonce here to trigger one-off actions via
  // the same UserDefaults KVO path that carries tokens.
  private let sentinelForceSync = "forceSyncNonce"
  private let sentinelPing = "pingNonce"
  private var defaults: UserDefaults?

  private var pollTimer: Timer?
  private var lastPayload: [String: String] = [:]
  private var lastForceSyncNonce: String = ""
  private var lastPingNonce: String = ""

  private override init() {
    super.init()
    watchBridgeLog.info("init")
    guard WCSession.isSupported() else {
      watchBridgeLog.error("WCSession not supported")
      return
    }
    defaults = UserDefaults(suiteName: appGroup)
    WCSession.default.delegate = self
    WCSession.default.activate()
    startObserving()
  }

  private func startObserving() {
    // Observe all UserDefaults changes — the JS ExtensionStorage writes via its
    // own UserDefaults instance, so filtering by object would miss them.
    NotificationCenter.default.addObserver(
      self,
      selector: #selector(defaultsDidChange(_:)),
      name: UserDefaults.didChangeNotification,
      object: nil
    )

    // Safety net: poll every 2s in case KVO misses a write (e.g., from a
    // separate UserDefaults instance that doesn't post didChange).
    DispatchQueue.main.async { [weak self] in
      self?.pollTimer = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { [weak self] _ in
        self?.handleSentinels()
        self?.forwardToWatch()
      }
    }
  }

  @objc private func defaultsDidChange(_ notification: Notification) {
    handleSentinels()
    forwardToWatch()
  }

  /// Checks the JS-driven action sentinels (forceSyncNonce, pingNonce) and
  /// triggers the corresponding WCSession action when the value bumps.
  /// Using sentinel keys keeps all JS↔native bridging on a single channel
  /// (App Group UserDefaults) — no native-module RCT bridging needed.
  private func handleSentinels() {
    guard let defaults = defaults else { return }

    if let nonce = defaults.string(forKey: sentinelForceSync), nonce != lastForceSyncNonce, !nonce.isEmpty {
      lastForceSyncNonce = nonce
      watchBridgeLog.info("forceSync nonce=\\(nonce, privacy: .public) — clearing dedupe cache")
      // Clear dedupe cache so forwardToWatch sends even if tokens didn't change.
      lastPayload = [:]
    }

    if let nonce = defaults.string(forKey: sentinelPing), nonce != lastPingNonce, !nonce.isEmpty {
      lastPingNonce = nonce
      guard WCSession.default.activationState == .activated else {
        watchBridgeLog.info("ping skipped — session not activated")
        return
      }
      guard WCSession.default.isReachable else {
        watchBridgeLog.info("ping skipped — watch not reachable")
        return
      }
      watchBridgeLog.info("ping send nonce=\\(nonce, privacy: .public)")
      WCSession.default.sendMessage(
        ["type": "ping", "nonce": nonce],
        replyHandler: nil,
        errorHandler: { error in
          watchBridgeLog.error("ping sendMessage error: \\(error.localizedDescription, privacy: .public)")
        }
      )
    }
  }

  /// Dispatches the current pairing / installed state of the paired Apple Watch
  /// to JavaScript so the app can render a one-time "install the companion"
  /// prompt when a watch is paired but the companion hasn't been installed.
  private func emitWatchState() {
    guard WCSession.default.activationState == .activated else { return }
    let payload: [String: Any] = [
      "isPaired": WCSession.default.isPaired,
      "isWatchAppInstalled": WCSession.default.isWatchAppInstalled,
      "isReachable": WCSession.default.isReachable,
    ]
    DispatchQueue.main.async {
      if let bridge = RCTBridge.current() {
        bridge.enqueueJSCall(
          "RCTDeviceEventEmitter",
          method: "emit",
          args: ["watchState", payload],
          completion: nil
        )
        watchBridgeLog.info("dispatched watchState paired=\\(WCSession.default.isPaired, privacy: .public) installed=\\(WCSession.default.isWatchAppInstalled, privacy: .public) reachable=\\(WCSession.default.isReachable, privacy: .public) to RN")
      }
    }
  }

  private func forwardToWatch() {
    guard
      WCSession.default.activationState == .activated,
      WCSession.default.isPaired,
      WCSession.default.isWatchAppInstalled,
      let defaults = defaults
    else { return }

    var stringPayload: [String: String] = [:]
    for key in watchedKeys {
      if let value = defaults.string(forKey: key) {
        stringPayload[key] = value
      }
    }
    guard !stringPayload.isEmpty else { return }

    // Dedupe: only forward if the data actually changed since last send.
    if stringPayload == lastPayload { return }
    lastPayload = stringPayload

    let payload: [String: Any] = stringPayload

    watchBridgeLog.info("forwarding payload with keys: \\(payload.keys.sorted(), privacy: .public)")

    // Fast path: send a message directly when the watch app is in the foreground.
    if WCSession.default.isReachable {
      WCSession.default.sendMessage(payload, replyHandler: nil, errorHandler: { error in
        watchBridgeLog.error("sendMessage error: \\(error.localizedDescription, privacy: .public)")
      })
    }

    // Persistent path: updateApplicationContext works in simulator and delivers
    // the latest context to the watch app on next foreground (replaces previous value).
    do {
      try WCSession.default.updateApplicationContext(payload)
      watchBridgeLog.info("updateApplicationContext succeeded")
    } catch {
      watchBridgeLog.error("updateApplicationContext error: \\(error.localizedDescription, privacy: .public)")
    }
  }

  deinit {
    NotificationCenter.default.removeObserver(self)
  }
}

// MARK: - WCSessionDelegate

extension WatchSessionBridge: WCSessionDelegate {

  func session(
    _ session: WCSession,
    activationDidCompleteWith activationState: WCSessionActivationState,
    error: Error?
  ) {
    if let error = error {
      watchBridgeLog.error("Activation error: \\(error.localizedDescription, privacy: .public)")
      return
    }
    watchBridgeLog.info("activation complete: state=\\(activationState.rawValue, privacy: .public) paired=\\(WCSession.default.isPaired, privacy: .public) installed=\\(WCSession.default.isWatchAppInstalled, privacy: .public) reachable=\\(WCSession.default.isReachable, privacy: .public)")
    if activationState == .activated {
      forwardToWatch()
      emitWatchState()
    }
  }

  func sessionDidBecomeInactive(_ session: WCSession) {
    // Required on iOS — nothing to do
  }

  func sessionDidDeactivate(_ session: WCSession) {
    // Required on iOS — reactivate to support Apple Watch switching
    WCSession.default.activate()
  }

  /// Fires when the user pairs/unpairs a watch or installs/uninstalls the
  /// companion app while the phone app is running. Re-emitting the state lets
  /// the install prompt react live without requiring a cold restart.
  func sessionWatchStateDidChange(_ session: WCSession) {
    watchBridgeLog.info("sessionWatchStateDidChange: paired=\\(WCSession.default.isPaired, privacy: .public) installed=\\(WCSession.default.isWatchAppInstalled, privacy: .public)")
    emitWatchState()
  }

  /// Fires when the watch app foregrounds/backgrounds. Re-emit so the Profile
  /// screen's Test-connection button enables/disables live.
  func sessionReachabilityDidChange(_ session: WCSession) {
    watchBridgeLog.info("sessionReachabilityDidChange: reachable=\\(WCSession.default.isReachable, privacy: .public)")
    emitWatchState()
  }

  /// Called when the watch sends a message — currently "drinkLogged" (sync
  /// nudge) and "pong" (connection-test reply). Forward to JavaScript as a
  /// device event so React Query / the ping promise resolver can react.
  func session(_ session: WCSession, didReceiveMessage message: [String: Any]) {
    watchBridgeLog.info("didReceiveMessage: \\(message, privacy: .public)")
    guard let type = message["type"] as? String else { return }
    var payload: [String: Any] = ["type": type]
    if let nonce = message["nonce"] as? String {
      payload["nonce"] = nonce
    }
    DispatchQueue.main.async {
      if let bridge = RCTBridge.current() {
        bridge.enqueueJSCall(
          "RCTDeviceEventEmitter",
          method: "emit",
          args: ["watchRemoteEvent", payload],
          completion: nil
        )
        watchBridgeLog.info("dispatched watchRemoteEvent type=\\(type, privacy: .public) to RN")
      } else {
        watchBridgeLog.error("no RCTBridge.current() — event dropped")
      }
    }
  }
}
`;

// Inserted right after the #endif that closes the #if os(iOS) || os(tvOS) block
// in application(_:didFinishLaunchingWithOptions:).
const INIT_CALL =
  "\n    // Activate the WatchConnectivity bridge so session tokens written to the\n    // shared App Group are forwarded to the paired Apple Watch.\n    _ = WatchSessionBridge.shared\n";

/**
 * Anchor used for the init-call insertion. Includes the full
 * factory.startReactNative(...) call followed by its closing #endif so the
 * match is structurally unique inside AppDelegate.swift. A bare "#endif"
 * would also match the #if DEBUG block later in the file, and whether it
 * hit the correct one would depend on source order — fragile across Expo
 * template changes.
 *
 * Whitespace must match the Expo-generated template exactly (4-space indent
 * on the call, 6-space indent on the named arguments, "#endif" at column 0).
 */
const INIT_ANCHOR = `    factory.startReactNative(
      withModuleName: "main",
      in: window,
      launchOptions: launchOptions)
#endif`;

module.exports = function withWatchSessionBridge(config) {
  return withDangerousMod(config, [
    "ios",
    async (cfg) => {
      const appDelegatePath = path.join(
        cfg.modRequest.platformProjectRoot,
        "ProstCounter",
        "AppDelegate.swift",
      );

      let src = fs.readFileSync(appDelegatePath, "utf-8");

      if (src.includes("WatchSessionBridge")) {
        console.log(
          "withWatchSessionBridge: AppDelegate.swift already contains WatchSessionBridge — skipping.",
        );
        return cfg;
      }

      // 1. Inject the activation call after the closing #endif of the
      //    #if os(iOS) || os(tvOS) block inside didFinishLaunchingWithOptions.
      //    Must be unambiguous — fail loudly if the Expo template drifted,
      //    rather than silently injecting at the wrong spot (or not at all).
      const anchorMatches = src.split(INIT_ANCHOR).length - 1;
      if (anchorMatches === 0) {
        throw new Error(
          "withWatchSessionBridge: INIT_ANCHOR not found in AppDelegate.swift. " +
            "The Expo template has likely changed — update the anchor in this plugin.",
        );
      }
      if (anchorMatches > 1) {
        throw new Error(
          `withWatchSessionBridge: INIT_ANCHOR matched ${anchorMatches} times in AppDelegate.swift — expected exactly 1.`,
        );
      }
      src = src.replace(INIT_ANCHOR, INIT_ANCHOR + INIT_CALL);

      // 2. Append the WatchSessionBridge class as top-level code at end of file.
      src = src + "\n" + BRIDGE_CLASS_SNIPPET;

      fs.writeFileSync(appDelegatePath, src, "utf-8");
      console.log(
        "withWatchSessionBridge: Injected WatchSessionBridge into AppDelegate.swift.",
      );

      return cfg;
    },
  ]);
};
