name: Novu Sync

on:
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - 'novu/workflows/**'
      - 'scripts/novu-sync.ts'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.14.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm novu:sync
        env:
          NOVU_API_KEY: ${{ secrets.NOVU_API_KEY }}


